config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  	member do
  		put :change
  	end
  end

  devise_for :users
  get 'pages/home'

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	validates :user_id, presence: true 
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
       redirect_to tasks_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
    @open = current_user.tasks.where(state:  "open")
    @wip = current_user.tasks.where(state:  "wip")
    @closed = current_user.tasks.where(state:  "closed")
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
#    @task = Task.new(task_params)
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format| 
      format.html { redirect_to tasks_path, notice: "Task updated"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav>  
   <div class="nav-wrapper">
     <%= link_to 'Kanban', root_path, class: "brand-logo" %>
     <ul id="nav-mobile" class="right hide-on-med-and-down">
     		<% if current_user %>
     			<li><%= link_to 'Manage Account', edit_user_registration_path %></li>
     			<li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
     		<% else %>
     			<li><%= link_to 'Sign In', new_user_session_path %></li>
     		<% end %>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanban</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <p class="notice"><%= notice %></p><br><p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">  
  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Kanban</span>
        <p>Welcome to Kanban, the simple, Kanban inspired to-do list.</p>
      </div>
      <div class="card-action">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="card blue-grey darken-1">
  <div class="card-panel white">
    <%= link_to edit_task_path(task) do %>
    Created <%= time_ago_in_words(task.created_at) %> ago 
    <% end %>
    <%= link_to "<i class='fa fa-trash-o' aria-hidden='true'></i>".html_safe, task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: "right" %>
  </div>
  <div class="card-content white-text">
    <%= task.content %>
    <% if task.state == 'wip' %> <%= link_to "<i class ='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "open"), method: :put, class:"btn red", style: "width:45%;" %><%= link_to "<i class ='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "closed"), method: :put, class:"btn right", style: "width:45%;"  %>

<% elsif task.state == 'closed' %>
      <%= link_to "<i class ='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "wip"), method: :put, class:"btn btn-block red" %>
    <% else %>
      <%= link_to "<i class ='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "wip"), method: :put, class:"btn btn-block"  %>
    <% end %>
   </div>
 </div>

app/views/tasks/edit.html.erb
<div class=”container”>
	<h1>Editing Task</h1>

	<%= render 'form', task: @task %>

	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col l4 s12">
    <h3>Open</h3>
      <%= render @open %>
    </div>
    <div class="col l4 s12">
    <h3>WIP</h3>
      <%= render @wip %>
    </div>
    <div class="col l4 s12">
    <h3>Closed</h3>
      <%= render @closed %>
    </div>
  </div>
  <div class="row">
    <%= link_to 'New Task', new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class=”container”>
  <%= link_to "<i class='fa fa-plus' aria-hidden='true'></i>".html_safe, new_task_path, class: "btn-floating btn-large blue" %>
	<h1>New Task</h1>

	<%= render 'form', task: @task %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>